### ISSUE TITLE
Bug report for motoE6



### ISSUE THREAD

**Issue by stacky1956** [maxieds/ChameleonMiniLiveDebugger#38]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by maxieds** [comment]
@stacky1956 
I do not understand your question. You have not provided me with enough details to even understand what the problem is you are having. 

When you file future bug reports, **PLEASE** make sure to include an adequate amount of details like how you caused the crash (or what button you clicked) so I can follow along!
