### ISSUE TITLE
V1. 2.9-Free

### ISSUE THREAD

**Issue by stacky1956** [maxieds/ChameleonMiniLiveDebugger#39]
When the phone Freeze's the only thing that I can do is hold the power button down for about 20 to 30 sec to get a it to. Restart .

**Comment by maxieds** [comment]
@stacky1956 
I do not know of the exact source. A number of releases have been made since **v1.2.9** (both on Play Store and [via the GH releases page](https://github.com/maxieds/ChameleonMiniLiveDebugger/releases/latest)). You will need to upgrade to the latest version to obtain active support for the problems you have running the application. 

(Closing, please re-open, or post a new issue if the problems persist after upgrading)
