### ISSUE TITLE
Crash Report (CMLD 1.3.6-free):  Neither user 10364 nor current process has android.permission.BLUETOOTH_ADMIN. [Android 10, SDK 29]

### ISSUE THREAD

**Issue by fbsnake** [maxieds/ChameleonMiniLiveDebugger#52]
@maxieds:

**Crash data summary:**
* *CMLD Version*: v1.3.6-free (8178:98)
* *CMLD GitHub Commit*: 9eec3d4bd94b @ Thu Apr 29 13:50:12 2021 -0400
* *CMLD Build Date*: 2021-04-29-135246
* *Chameleon Type*: <UNKNOWN>
* *Serial Connection Type*: NULL
* *Chameleon Config*: NOT SET
* *Chameleon Logmode*: NOT SET
* *Chameleon Timeout*: NOT SET
* *Android Device*: HWMAR
* *Android Manufacturer*: HUAWEI
* *Android Brand*: HUAWEI
* *Android Product*: MAR-LX1AEEA
* *Android Model*: MAR-LX1A
* *Android Hardware*: kirin710
* *Android SDK*: 29
* *Android OS Release*: HUAWEI/MAR-LX1AEEA/HWMAR:10/HUAWEIMAR-L21A/10.0.0.233C431:user/release-keys 10 (REL / 10.0.0.275C431)
* *Android Board*: MAR
* *Android Type*: user

**Stack trace:**
```java**Exception Message:** Need BLUETOOTH ADMIN permission: Neither user 10364 nor current process has android.permission.BLUETOOTH_ADMIN.



Detailed Stack Trace:
java.lang.SecurityException: Need BLUETOOTH ADMIN permission: Neither user 10364 nor current process has android.permission.BLUETOOTH_ADMIN.
	at android.os.Parcel.
     createException( Parcel.java:2071 )
	at android.os.Parcel.
     readException( Parcel.java:2039 )
	at android.os.Parcel.
     readException( Parcel.java:1987 )
	at android.bluetooth.IBluetooth$Stub$Proxy.
     cancelDiscovery( IBluetooth.java:2187 )
	at android.bluetooth.BluetoothAdapter.
     cancelDiscovery( BluetoothAdapter.java:1680 )
	at com.maxieds.chameleonminilivedebugger.e.
     r( BluetoothGattConnector.java:2 )
	at com.maxieds.chameleonminilivedebugger.f.
     s( BluetoothSerialInterface.java:1 )
	at com.maxieds.chameleonminilivedebugger.n.
     d( ChameleonSettings.java:2 )
	at com.maxieds.chameleonminilivedebugger.c0$a.
     onClick( UITabUtils.java:3 )
	at android.view.View.
     performClick( View.java:7192 )
	at android.view.View.
     performClickInternal( View.java:7166 )
	at android.view.View.access$3500( View.java:824 )
	at android.view.View$PerformClick.
     run( View.java:27592 )
	at android.os.Handler.
     handleCallback( Handler.java:888 )
	at android.os.Handler.
     dispatchMessage( Handler.java:100 )
	at android.os.Looper.
     loop( Looper.java:213 )
	at android.app.ActivityThread.
     main( ActivityThread.java:8178 )
	at java.lang.reflect.Method.invoke( Native Method )
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.
     run( RuntimeInit.java:513 )
	at com.android.internal.os.ZygoteInit.
     main( ZygoteInit.java:1101 )

```

**Additional comments:**
*NONE -- Please fill in more details about how you generated this error, like what actions you took before this screen is displayed. Did the error happen on launch of the application? Did you click a button or switch tabs? Any extra details about how the error happened are useful to fixing the issue in future releases.*

**Comment by maxieds** [comment]
@fbsnake 
I need more information to determine the severity of the bug fix required. Did the application crash on start up due to the lacking BlueTooth permissions, or did it crash after you navigated to the settings and started turning on the non-default BT options? 

I swear that I really do not get why this many users of the application are that interested in the BT. It's really a beast, and caused RF interference nightmares for me working on my DESFire emulation mods for the Chameleon firmware last year. That, and I also note, that the Proxgrind vendors have absolutely NO INTEREST in sharing the behind-closed-doors stack underneath their proprietary BT firmware for these devices. If y'all do eventually want my CMLD app to work well with their BT hardware, please by all means, complain up stream to them! The KAOS devices over a small serial USB connection are what I use personally for development. 

-- MDS
